/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class matrix_client_ZHTClient */

#ifndef _Included_matrix_client_ZHTClient
#define _Included_matrix_client_ZHTClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     matrix_client_ZHTClient
 * Method:    lookUp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_matrix_client_ZHTClient_lookUp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     matrix_client_ZHTClient
 * Method:    insertZHT
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_matrix_client_ZHTClient_insertZHT
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     matrix_client_ZHTClient
 * Method:    compareSwap
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_matrix_client_ZHTClient_compareSwap
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
