// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metatask.proto

package matrix.protocol;

public final class Metatask {
  private Metatask() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaskMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:matrix.protocol.TaskMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string taskId = 1;</code>
     */
    boolean hasTaskId();
    /**
     * <code>required string taskId = 1;</code>
     */
    java.lang.String getTaskId();
    /**
     * <code>required string taskId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>required string user = 2;</code>
     */
    boolean hasUser();
    /**
     * <code>required string user = 2;</code>
     */
    java.lang.String getUser();
    /**
     * <code>required string user = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <code>required string dir = 3;</code>
     */
    boolean hasDir();
    /**
     * <code>required string dir = 3;</code>
     */
    java.lang.String getDir();
    /**
     * <code>required string dir = 3;</code>
     */
    com.google.protobuf.ByteString
        getDirBytes();

    /**
     * <code>required string cmd = 4;</code>
     */
    boolean hasCmd();
    /**
     * <code>required string cmd = 4;</code>
     */
    java.lang.String getCmd();
    /**
     * <code>required string cmd = 4;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>required int64 dataLength = 5;</code>
     */
    boolean hasDataLength();
    /**
     * <code>required int64 dataLength = 5;</code>
     */
    long getDataLength();
  }
  /**
   * Protobuf type {@code matrix.protocol.TaskMsg}
   */
  public  static final class TaskMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:matrix.protocol.TaskMsg)
      TaskMsgOrBuilder {
    // Use TaskMsg.newBuilder() to construct.
    private TaskMsg(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TaskMsg() {
      taskId_ = "";
      user_ = "";
      dir_ = "";
      cmd_ = "";
      dataLength_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              taskId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              user_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              dir_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              cmd_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              dataLength_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return matrix.protocol.Metatask.internal_static_matrix_protocol_TaskMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return matrix.protocol.Metatask.internal_static_matrix_protocol_TaskMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              matrix.protocol.Metatask.TaskMsg.class, matrix.protocol.Metatask.TaskMsg.Builder.class);
    }

    public static final com.google.protobuf.Parser<TaskMsg> PARSER =
        new com.google.protobuf.AbstractParser<TaskMsg>() {
      public TaskMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TaskMsg(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaskMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TASKID_FIELD_NUMBER = 1;
    private java.lang.Object taskId_;
    /**
     * <code>required string taskId = 1;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    private java.lang.Object user_;
    /**
     * <code>required string user = 2;</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string user = 2;</code>
     */
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          user_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string user = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIR_FIELD_NUMBER = 3;
    private java.lang.Object dir_;
    /**
     * <code>required string dir = 3;</code>
     */
    public boolean hasDir() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string dir = 3;</code>
     */
    public java.lang.String getDir() {
      java.lang.Object ref = dir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dir = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDirBytes() {
      java.lang.Object ref = dir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 4;
    private java.lang.Object cmd_;
    /**
     * <code>required string cmd = 4;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string cmd = 4;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cmd = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATALENGTH_FIELD_NUMBER = 5;
    private long dataLength_;
    /**
     * <code>required int64 dataLength = 5;</code>
     */
    public boolean hasDataLength() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 dataLength = 5;</code>
     */
    public long getDataLength() {
      return dataLength_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDataLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTaskIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDirBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCmdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, dataLength_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTaskIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDirBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCmdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, dataLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static matrix.protocol.Metatask.TaskMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static matrix.protocol.Metatask.TaskMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static matrix.protocol.Metatask.TaskMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static matrix.protocol.Metatask.TaskMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return defaultInstance.toBuilder();
    }
    public static Builder newBuilder(matrix.protocol.Metatask.TaskMsg prototype) {
      return defaultInstance.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == defaultInstance
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code matrix.protocol.TaskMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:matrix.protocol.TaskMsg)
        matrix.protocol.Metatask.TaskMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return matrix.protocol.Metatask.internal_static_matrix_protocol_TaskMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return matrix.protocol.Metatask.internal_static_matrix_protocol_TaskMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                matrix.protocol.Metatask.TaskMsg.class, matrix.protocol.Metatask.TaskMsg.Builder.class);
      }

      // Construct using matrix.protocol.Metatask.TaskMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        user_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        dir_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dataLength_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return matrix.protocol.Metatask.internal_static_matrix_protocol_TaskMsg_descriptor;
      }

      public matrix.protocol.Metatask.TaskMsg getDefaultInstanceForType() {
        return matrix.protocol.Metatask.TaskMsg.getDefaultInstance();
      }

      public matrix.protocol.Metatask.TaskMsg build() {
        matrix.protocol.Metatask.TaskMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public matrix.protocol.Metatask.TaskMsg buildPartial() {
        matrix.protocol.Metatask.TaskMsg result = new matrix.protocol.Metatask.TaskMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dir_ = dir_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dataLength_ = dataLength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof matrix.protocol.Metatask.TaskMsg) {
          return mergeFrom((matrix.protocol.Metatask.TaskMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(matrix.protocol.Metatask.TaskMsg other) {
        if (other == matrix.protocol.Metatask.TaskMsg.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          bitField0_ |= 0x00000001;
          taskId_ = other.taskId_;
          onChanged();
        }
        if (other.hasUser()) {
          bitField0_ |= 0x00000002;
          user_ = other.user_;
          onChanged();
        }
        if (other.hasDir()) {
          bitField0_ |= 0x00000004;
          dir_ = other.dir_;
          onChanged();
        }
        if (other.hasCmd()) {
          bitField0_ |= 0x00000008;
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.hasDataLength()) {
          setDataLength(other.getDataLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskId()) {
          
          return false;
        }
        if (!hasUser()) {
          
          return false;
        }
        if (!hasDir()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasDataLength()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        matrix.protocol.Metatask.TaskMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (matrix.protocol.Metatask.TaskMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <code>required string taskId = 1;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <code>required string user = 2;</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string user = 2;</code>
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            user_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string user = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string user = 2;</code>
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 2;</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000002);
        user_ = getDefaultInstance().getUser();
        onChanged();
        return this;
      }
      /**
       * <code>required string user = 2;</code>
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        user_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dir_ = "";
      /**
       * <code>required string dir = 3;</code>
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string dir = 3;</code>
       */
      public java.lang.String getDir() {
        java.lang.Object ref = dir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string dir = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDirBytes() {
        java.lang.Object ref = dir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dir = 3;</code>
       */
      public Builder setDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dir = 3;</code>
       */
      public Builder clearDir() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dir_ = getDefaultInstance().getDir();
        onChanged();
        return this;
      }
      /**
       * <code>required string dir = 3;</code>
       */
      public Builder setDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>required string cmd = 4;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string cmd = 4;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string cmd = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cmd = 4;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cmd = 4;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>required string cmd = 4;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cmd_ = value;
        onChanged();
        return this;
      }

      private long dataLength_ ;
      /**
       * <code>required int64 dataLength = 5;</code>
       */
      public boolean hasDataLength() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 dataLength = 5;</code>
       */
      public long getDataLength() {
        return dataLength_;
      }
      /**
       * <code>required int64 dataLength = 5;</code>
       */
      public Builder setDataLength(long value) {
        bitField0_ |= 0x00000010;
        dataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 dataLength = 5;</code>
       */
      public Builder clearDataLength() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dataLength_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:matrix.protocol.TaskMsg)
    }

    // @@protoc_insertion_point(class_scope:matrix.protocol.TaskMsg)
    private static final matrix.protocol.Metatask.TaskMsg defaultInstance;
    static {
      defaultInstance = new matrix.protocol.Metatask.TaskMsg();
    }

    public static matrix.protocol.Metatask.TaskMsg getDefaultInstance() {
      return defaultInstance;
    }

    public matrix.protocol.Metatask.TaskMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    static {
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_matrix_protocol_TaskMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_matrix_protocol_TaskMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016metatask.proto\022\017matrix.protocol\"U\n\007Tas" +
      "kMsg\022\016\n\006taskId\030\001 \002(\t\022\014\n\004user\030\002 \002(\t\022\013\n\003di" +
      "r\030\003 \002(\t\022\013\n\003cmd\030\004 \002(\t\022\022\n\ndataLength\030\005 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_matrix_protocol_TaskMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_matrix_protocol_TaskMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_matrix_protocol_TaskMsg_descriptor,
        new java.lang.String[] { "TaskId", "User", "Dir", "Cmd", "DataLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
