/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package matrix.zht;

public class cpp_zhtclientJNI {
  public final static native long new_ZHTClient__SWIG_0();
  public final static native long new_ZHTClient__SWIG_1(String jarg1, String jarg2);
  public final static native void delete_ZHTClient(long jarg1);
  public final static native int ZHTClient_init(long jarg1, ZHTClient jarg1_, String jarg2, String jarg3);
  public final static native String ZHTClient_lookup(long jarg1, ZHTClient jarg1_, String jarg2);
  public final static native int ZHTClient_insert(long jarg1, ZHTClient jarg1_, String jarg2, String jarg3);
  public final static native int ZHTClient_compare_swap_int(long jarg1, ZHTClient jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native String ZHTClient_compare_swap_string(long jarg1, ZHTClient jarg1_, String jarg2, String jarg3, String jarg4);
}
