// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metazht.proto

package matrix.protocol;

public final class Metazht {
  private Metazht() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:matrix.protocol.Value)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional int64 inDegree = 2;</code>
     */
    boolean hasInDegree();
    /**
     * <code>optional int64 inDegree = 2;</code>
     */
    long getInDegree();

    /**
     * <code>repeated string parents = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getParentsList();
    /**
     * <code>repeated string parents = 3;</code>
     */
    int getParentsCount();
    /**
     * <code>repeated string parents = 3;</code>
     */
    java.lang.String getParents(int index);
    /**
     * <code>repeated string parents = 3;</code>
     */
    com.google.protobuf.ByteString
        getParentsBytes(int index);

    /**
     * <code>repeated string children = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getChildrenList();
    /**
     * <code>repeated string children = 4;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated string children = 4;</code>
     */
    java.lang.String getChildren(int index);
    /**
     * <code>repeated string children = 4;</code>
     */
    com.google.protobuf.ByteString
        getChildrenBytes(int index);

    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getDataNameListList();
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    int getDataNameListCount();
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    java.lang.String getDataNameList(int index);
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataNameListBytes(int index);

    /**
     * <code>repeated int64 dataSize = 6;</code>
     */
    java.util.List<java.lang.Long> getDataSizeList();
    /**
     * <code>repeated int64 dataSize = 6;</code>
     */
    int getDataSizeCount();
    /**
     * <code>repeated int64 dataSize = 6;</code>
     */
    long getDataSize(int index);

    /**
     * <code>optional int64 allDataSize = 7;</code>
     */
    boolean hasAllDataSize();
    /**
     * <code>optional int64 allDataSize = 7;</code>
     */
    long getAllDataSize();

    /**
     * <code>optional int64 taskLength = 8;</code>
     */
    boolean hasTaskLength();
    /**
     * <code>optional int64 taskLength = 8;</code>
     */
    long getTaskLength();

    /**
     * <code>optional int64 numTaskFin = 9;</code>
     */
    boolean hasNumTaskFin();
    /**
     * <code>optional int64 numTaskFin = 9;</code>
     */
    long getNumTaskFin();

    /**
     * <code>optional int64 numWorkSteal = 10;</code>
     */
    boolean hasNumWorkSteal();
    /**
     * <code>optional int64 numWorkSteal = 10;</code>
     */
    long getNumWorkSteal();

    /**
     * <code>optional int64 numWorkStealFail = 11;</code>
     */
    boolean hasNumWorkStealFail();
    /**
     * <code>optional int64 numWorkStealFail = 11;</code>
     */
    long getNumWorkStealFail();

    /**
     * <code>optional int32 numTaskWait = 12;</code>
     */
    boolean hasNumTaskWait();
    /**
     * <code>optional int32 numTaskWait = 12;</code>
     */
    int getNumTaskWait();

    /**
     * <code>optional int32 numTaskReady = 13;</code>
     */
    boolean hasNumTaskReady();
    /**
     * <code>optional int32 numTaskReady = 13;</code>
     */
    int getNumTaskReady();

    /**
     * <code>optional int32 numCoreAvilable = 14;</code>
     */
    boolean hasNumCoreAvilable();
    /**
     * <code>optional int32 numCoreAvilable = 14;</code>
     */
    int getNumCoreAvilable();

    /**
     * <code>optional int32 numAllCore = 15;</code>
     */
    boolean hasNumAllCore();
    /**
     * <code>optional int32 numAllCore = 15;</code>
     */
    int getNumAllCore();

    /**
     * <code>optional int64 outputSize = 16;</code>
     */
    boolean hasOutputSize();
    /**
     * <code>optional int64 outputSize = 16;</code>
     */
    long getOutputSize();

    /**
     * <code>optional int64 submitTime = 17;</code>
     */
    boolean hasSubmitTime();
    /**
     * <code>optional int64 submitTime = 17;</code>
     */
    long getSubmitTime();
  }
  /**
   * Protobuf type {@code matrix.protocol.Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:matrix.protocol.Value)
      ValueOrBuilder {
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Value(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Value defaultInstance;
    public static Value getDefaultInstance() {
      return defaultInstance;
    }

    public Value getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Value(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              inDegree_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                parents_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              parents_.add(bs);
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                children_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              children_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                dataNameList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              dataNameList_.add(bs);
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                dataSize_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000020;
              }
              dataSize_.add(input.readInt64());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                dataSize_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000020;
              }
              while (input.getBytesUntilLimit() > 0) {
                dataSize_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 56: {
              bitField0_ |= 0x00000004;
              allDataSize_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000008;
              taskLength_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000010;
              numTaskFin_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000020;
              numWorkSteal_ = input.readInt64();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000040;
              numWorkStealFail_ = input.readInt64();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000080;
              numTaskWait_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00000100;
              numTaskReady_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00000200;
              numCoreAvilable_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000400;
              numAllCore_ = input.readInt32();
              break;
            }
            case 128: {
              bitField0_ |= 0x00000800;
              outputSize_ = input.readInt64();
              break;
            }
            case 136: {
              bitField0_ |= 0x00001000;
              submitTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          parents_ = parents_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          children_ = children_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          dataNameList_ = dataNameList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          dataSize_ = java.util.Collections.unmodifiableList(dataSize_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return matrix.protocol.Metazht.internal_static_matrix_protocol_Value_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return matrix.protocol.Metazht.internal_static_matrix_protocol_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              matrix.protocol.Metazht.Value.class, matrix.protocol.Metazht.Value.Builder.class);
    }

    public static com.google.protobuf.Parser<Value> PARSER =
        new com.google.protobuf.AbstractParser<Value>() {
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Value(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEGREE_FIELD_NUMBER = 2;
    private long inDegree_;
    /**
     * <code>optional int64 inDegree = 2;</code>
     */
    public boolean hasInDegree() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 inDegree = 2;</code>
     */
    public long getInDegree() {
      return inDegree_;
    }

    public static final int PARENTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList parents_;
    /**
     * <code>repeated string parents = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParentsList() {
      return parents_;
    }
    /**
     * <code>repeated string parents = 3;</code>
     */
    public int getParentsCount() {
      return parents_.size();
    }
    /**
     * <code>repeated string parents = 3;</code>
     */
    public java.lang.String getParents(int index) {
      return parents_.get(index);
    }
    /**
     * <code>repeated string parents = 3;</code>
     */
    public com.google.protobuf.ByteString
        getParentsBytes(int index) {
      return parents_.getByteString(index);
    }

    public static final int CHILDREN_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList children_;
    /**
     * <code>repeated string children = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated string children = 4;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated string children = 4;</code>
     */
    public java.lang.String getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated string children = 4;</code>
     */
    public com.google.protobuf.ByteString
        getChildrenBytes(int index) {
      return children_.getByteString(index);
    }

    public static final int DATANAMELIST_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList dataNameList_;
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getDataNameListList() {
      return dataNameList_;
    }
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    public int getDataNameListCount() {
      return dataNameList_.size();
    }
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    public java.lang.String getDataNameList(int index) {
      return dataNameList_.get(index);
    }
    /**
     * <code>repeated string dataNameList = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataNameListBytes(int index) {
      return dataNameList_.getByteString(index);
    }

    public static final int DATASIZE_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Long> dataSize_;
    /**
     * <code>repeated int64 dataSize = 6;</code>
     */
    public java.util.List<java.lang.Long>
        getDataSizeList() {
      return dataSize_;
    }
    /**
     * <code>repeated int64 dataSize = 6;</code>
     */
    public int getDataSizeCount() {
      return dataSize_.size();
    }
    /**
     * <code>repeated int64 dataSize = 6;</code>
     */
    public long getDataSize(int index) {
      return dataSize_.get(index);
    }

    public static final int ALLDATASIZE_FIELD_NUMBER = 7;
    private long allDataSize_;
    /**
     * <code>optional int64 allDataSize = 7;</code>
     */
    public boolean hasAllDataSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 allDataSize = 7;</code>
     */
    public long getAllDataSize() {
      return allDataSize_;
    }

    public static final int TASKLENGTH_FIELD_NUMBER = 8;
    private long taskLength_;
    /**
     * <code>optional int64 taskLength = 8;</code>
     */
    public boolean hasTaskLength() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 taskLength = 8;</code>
     */
    public long getTaskLength() {
      return taskLength_;
    }

    public static final int NUMTASKFIN_FIELD_NUMBER = 9;
    private long numTaskFin_;
    /**
     * <code>optional int64 numTaskFin = 9;</code>
     */
    public boolean hasNumTaskFin() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 numTaskFin = 9;</code>
     */
    public long getNumTaskFin() {
      return numTaskFin_;
    }

    public static final int NUMWORKSTEAL_FIELD_NUMBER = 10;
    private long numWorkSteal_;
    /**
     * <code>optional int64 numWorkSteal = 10;</code>
     */
    public boolean hasNumWorkSteal() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 numWorkSteal = 10;</code>
     */
    public long getNumWorkSteal() {
      return numWorkSteal_;
    }

    public static final int NUMWORKSTEALFAIL_FIELD_NUMBER = 11;
    private long numWorkStealFail_;
    /**
     * <code>optional int64 numWorkStealFail = 11;</code>
     */
    public boolean hasNumWorkStealFail() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 numWorkStealFail = 11;</code>
     */
    public long getNumWorkStealFail() {
      return numWorkStealFail_;
    }

    public static final int NUMTASKWAIT_FIELD_NUMBER = 12;
    private int numTaskWait_;
    /**
     * <code>optional int32 numTaskWait = 12;</code>
     */
    public boolean hasNumTaskWait() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 numTaskWait = 12;</code>
     */
    public int getNumTaskWait() {
      return numTaskWait_;
    }

    public static final int NUMTASKREADY_FIELD_NUMBER = 13;
    private int numTaskReady_;
    /**
     * <code>optional int32 numTaskReady = 13;</code>
     */
    public boolean hasNumTaskReady() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 numTaskReady = 13;</code>
     */
    public int getNumTaskReady() {
      return numTaskReady_;
    }

    public static final int NUMCOREAVILABLE_FIELD_NUMBER = 14;
    private int numCoreAvilable_;
    /**
     * <code>optional int32 numCoreAvilable = 14;</code>
     */
    public boolean hasNumCoreAvilable() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 numCoreAvilable = 14;</code>
     */
    public int getNumCoreAvilable() {
      return numCoreAvilable_;
    }

    public static final int NUMALLCORE_FIELD_NUMBER = 15;
    private int numAllCore_;
    /**
     * <code>optional int32 numAllCore = 15;</code>
     */
    public boolean hasNumAllCore() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 numAllCore = 15;</code>
     */
    public int getNumAllCore() {
      return numAllCore_;
    }

    public static final int OUTPUTSIZE_FIELD_NUMBER = 16;
    private long outputSize_;
    /**
     * <code>optional int64 outputSize = 16;</code>
     */
    public boolean hasOutputSize() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 outputSize = 16;</code>
     */
    public long getOutputSize() {
      return outputSize_;
    }

    public static final int SUBMITTIME_FIELD_NUMBER = 17;
    private long submitTime_;
    /**
     * <code>optional int64 submitTime = 17;</code>
     */
    public boolean hasSubmitTime() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int64 submitTime = 17;</code>
     */
    public long getSubmitTime() {
      return submitTime_;
    }

    private void initFields() {
      id_ = "";
      inDegree_ = 0L;
      parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dataNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dataSize_ = java.util.Collections.emptyList();
      allDataSize_ = 0L;
      taskLength_ = 0L;
      numTaskFin_ = 0L;
      numWorkSteal_ = 0L;
      numWorkStealFail_ = 0L;
      numTaskWait_ = 0;
      numTaskReady_ = 0;
      numCoreAvilable_ = 0;
      numAllCore_ = 0;
      outputSize_ = 0L;
      submitTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, inDegree_);
      }
      for (int i = 0; i < parents_.size(); i++) {
        output.writeBytes(3, parents_.getByteString(i));
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeBytes(4, children_.getByteString(i));
      }
      for (int i = 0; i < dataNameList_.size(); i++) {
        output.writeBytes(5, dataNameList_.getByteString(i));
      }
      for (int i = 0; i < dataSize_.size(); i++) {
        output.writeInt64(6, dataSize_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(7, allDataSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(8, taskLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(9, numTaskFin_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(10, numWorkSteal_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(11, numWorkStealFail_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(12, numTaskWait_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(13, numTaskReady_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(14, numCoreAvilable_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(15, numAllCore_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(16, outputSize_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt64(17, submitTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, inDegree_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parents_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parents_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getParentsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < children_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(children_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getChildrenList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dataNameList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(dataNameList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getDataNameListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dataSize_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(dataSize_.get(i));
        }
        size += dataSize;
        size += 1 * getDataSizeList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, allDataSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, taskLength_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, numTaskFin_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, numWorkSteal_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, numWorkStealFail_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, numTaskWait_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, numTaskReady_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, numCoreAvilable_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(15, numAllCore_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(16, outputSize_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(17, submitTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static matrix.protocol.Metazht.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static matrix.protocol.Metazht.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static matrix.protocol.Metazht.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static matrix.protocol.Metazht.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static matrix.protocol.Metazht.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static matrix.protocol.Metazht.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static matrix.protocol.Metazht.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static matrix.protocol.Metazht.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static matrix.protocol.Metazht.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static matrix.protocol.Metazht.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(matrix.protocol.Metazht.Value prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code matrix.protocol.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:matrix.protocol.Value)
        matrix.protocol.Metazht.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return matrix.protocol.Metazht.internal_static_matrix_protocol_Value_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return matrix.protocol.Metazht.internal_static_matrix_protocol_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                matrix.protocol.Metazht.Value.class, matrix.protocol.Metazht.Value.Builder.class);
      }

      // Construct using matrix.protocol.Metazht.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        inDegree_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        dataNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        dataSize_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        allDataSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        taskLength_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        numTaskFin_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        numWorkSteal_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        numWorkStealFail_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000400);
        numTaskWait_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        numTaskReady_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        numCoreAvilable_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        numAllCore_ = 0;
        bitField0_ = (bitField0_ & ~0x00004000);
        outputSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00008000);
        submitTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return matrix.protocol.Metazht.internal_static_matrix_protocol_Value_descriptor;
      }

      public matrix.protocol.Metazht.Value getDefaultInstanceForType() {
        return matrix.protocol.Metazht.Value.getDefaultInstance();
      }

      public matrix.protocol.Metazht.Value build() {
        matrix.protocol.Metazht.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public matrix.protocol.Metazht.Value buildPartial() {
        matrix.protocol.Metazht.Value result = new matrix.protocol.Metazht.Value(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.inDegree_ = inDegree_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          parents_ = parents_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parents_ = parents_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          children_ = children_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.children_ = children_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          dataNameList_ = dataNameList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.dataNameList_ = dataNameList_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          dataSize_ = java.util.Collections.unmodifiableList(dataSize_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.dataSize_ = dataSize_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000004;
        }
        result.allDataSize_ = allDataSize_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskLength_ = taskLength_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000010;
        }
        result.numTaskFin_ = numTaskFin_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000020;
        }
        result.numWorkSteal_ = numWorkSteal_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000040;
        }
        result.numWorkStealFail_ = numWorkStealFail_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000080;
        }
        result.numTaskWait_ = numTaskWait_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000100;
        }
        result.numTaskReady_ = numTaskReady_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00000200;
        }
        result.numCoreAvilable_ = numCoreAvilable_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00000400;
        }
        result.numAllCore_ = numAllCore_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.outputSize_ = outputSize_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.submitTime_ = submitTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof matrix.protocol.Metazht.Value) {
          return mergeFrom((matrix.protocol.Metazht.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(matrix.protocol.Metazht.Value other) {
        if (other == matrix.protocol.Metazht.Value.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasInDegree()) {
          setInDegree(other.getInDegree());
        }
        if (!other.parents_.isEmpty()) {
          if (parents_.isEmpty()) {
            parents_ = other.parents_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParentsIsMutable();
            parents_.addAll(other.parents_);
          }
          onChanged();
        }
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
        if (!other.dataNameList_.isEmpty()) {
          if (dataNameList_.isEmpty()) {
            dataNameList_ = other.dataNameList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDataNameListIsMutable();
            dataNameList_.addAll(other.dataNameList_);
          }
          onChanged();
        }
        if (!other.dataSize_.isEmpty()) {
          if (dataSize_.isEmpty()) {
            dataSize_ = other.dataSize_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDataSizeIsMutable();
            dataSize_.addAll(other.dataSize_);
          }
          onChanged();
        }
        if (other.hasAllDataSize()) {
          setAllDataSize(other.getAllDataSize());
        }
        if (other.hasTaskLength()) {
          setTaskLength(other.getTaskLength());
        }
        if (other.hasNumTaskFin()) {
          setNumTaskFin(other.getNumTaskFin());
        }
        if (other.hasNumWorkSteal()) {
          setNumWorkSteal(other.getNumWorkSteal());
        }
        if (other.hasNumWorkStealFail()) {
          setNumWorkStealFail(other.getNumWorkStealFail());
        }
        if (other.hasNumTaskWait()) {
          setNumTaskWait(other.getNumTaskWait());
        }
        if (other.hasNumTaskReady()) {
          setNumTaskReady(other.getNumTaskReady());
        }
        if (other.hasNumCoreAvilable()) {
          setNumCoreAvilable(other.getNumCoreAvilable());
        }
        if (other.hasNumAllCore()) {
          setNumAllCore(other.getNumAllCore());
        }
        if (other.hasOutputSize()) {
          setOutputSize(other.getOutputSize());
        }
        if (other.hasSubmitTime()) {
          setSubmitTime(other.getSubmitTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        matrix.protocol.Metazht.Value parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (matrix.protocol.Metazht.Value) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long inDegree_ ;
      /**
       * <code>optional int64 inDegree = 2;</code>
       */
      public boolean hasInDegree() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 inDegree = 2;</code>
       */
      public long getInDegree() {
        return inDegree_;
      }
      /**
       * <code>optional int64 inDegree = 2;</code>
       */
      public Builder setInDegree(long value) {
        bitField0_ |= 0x00000002;
        inDegree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 inDegree = 2;</code>
       */
      public Builder clearInDegree() {
        bitField0_ = (bitField0_ & ~0x00000002);
        inDegree_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parents_ = new com.google.protobuf.LazyStringArrayList(parents_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParentsList() {
        return parents_.getUnmodifiableView();
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public int getParentsCount() {
        return parents_.size();
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public java.lang.String getParents(int index) {
        return parents_.get(index);
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public com.google.protobuf.ByteString
          getParentsBytes(int index) {
        return parents_.getByteString(index);
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public Builder setParents(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public Builder addParents(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public Builder addAllParents(
          java.lang.Iterable<java.lang.String> values) {
        ensureParentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, parents_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public Builder clearParents() {
        parents_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string parents = 3;</code>
       */
      public Builder addParentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParentsIsMutable();
        parents_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          children_ = new com.google.protobuf.LazyStringArrayList(children_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getChildrenList() {
        return children_.getUnmodifiableView();
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public int getChildrenCount() {
        return children_.size();
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public java.lang.String getChildren(int index) {
        return children_.get(index);
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public com.google.protobuf.ByteString
          getChildrenBytes(int index) {
        return children_.getByteString(index);
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public Builder setChildren(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public Builder addChildren(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<java.lang.String> values) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public Builder clearChildren() {
        children_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string children = 4;</code>
       */
      public Builder addChildrenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList dataNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDataNameListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          dataNameList_ = new com.google.protobuf.LazyStringArrayList(dataNameList_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getDataNameListList() {
        return dataNameList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public int getDataNameListCount() {
        return dataNameList_.size();
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public java.lang.String getDataNameList(int index) {
        return dataNameList_.get(index);
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataNameListBytes(int index) {
        return dataNameList_.getByteString(index);
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public Builder setDataNameList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataNameListIsMutable();
        dataNameList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public Builder addDataNameList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataNameListIsMutable();
        dataNameList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public Builder addAllDataNameList(
          java.lang.Iterable<java.lang.String> values) {
        ensureDataNameListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataNameList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public Builder clearDataNameList() {
        dataNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string dataNameList = 5;</code>
       */
      public Builder addDataNameListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDataNameListIsMutable();
        dataNameList_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> dataSize_ = java.util.Collections.emptyList();
      private void ensureDataSizeIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          dataSize_ = new java.util.ArrayList<java.lang.Long>(dataSize_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public java.util.List<java.lang.Long>
          getDataSizeList() {
        return java.util.Collections.unmodifiableList(dataSize_);
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public int getDataSizeCount() {
        return dataSize_.size();
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public long getDataSize(int index) {
        return dataSize_.get(index);
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public Builder setDataSize(
          int index, long value) {
        ensureDataSizeIsMutable();
        dataSize_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public Builder addDataSize(long value) {
        ensureDataSizeIsMutable();
        dataSize_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public Builder addAllDataSize(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureDataSizeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dataSize_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 dataSize = 6;</code>
       */
      public Builder clearDataSize() {
        dataSize_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }

      private long allDataSize_ ;
      /**
       * <code>optional int64 allDataSize = 7;</code>
       */
      public boolean hasAllDataSize() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 allDataSize = 7;</code>
       */
      public long getAllDataSize() {
        return allDataSize_;
      }
      /**
       * <code>optional int64 allDataSize = 7;</code>
       */
      public Builder setAllDataSize(long value) {
        bitField0_ |= 0x00000040;
        allDataSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 allDataSize = 7;</code>
       */
      public Builder clearAllDataSize() {
        bitField0_ = (bitField0_ & ~0x00000040);
        allDataSize_ = 0L;
        onChanged();
        return this;
      }

      private long taskLength_ ;
      /**
       * <code>optional int64 taskLength = 8;</code>
       */
      public boolean hasTaskLength() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 taskLength = 8;</code>
       */
      public long getTaskLength() {
        return taskLength_;
      }
      /**
       * <code>optional int64 taskLength = 8;</code>
       */
      public Builder setTaskLength(long value) {
        bitField0_ |= 0x00000080;
        taskLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 taskLength = 8;</code>
       */
      public Builder clearTaskLength() {
        bitField0_ = (bitField0_ & ~0x00000080);
        taskLength_ = 0L;
        onChanged();
        return this;
      }

      private long numTaskFin_ ;
      /**
       * <code>optional int64 numTaskFin = 9;</code>
       */
      public boolean hasNumTaskFin() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 numTaskFin = 9;</code>
       */
      public long getNumTaskFin() {
        return numTaskFin_;
      }
      /**
       * <code>optional int64 numTaskFin = 9;</code>
       */
      public Builder setNumTaskFin(long value) {
        bitField0_ |= 0x00000100;
        numTaskFin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 numTaskFin = 9;</code>
       */
      public Builder clearNumTaskFin() {
        bitField0_ = (bitField0_ & ~0x00000100);
        numTaskFin_ = 0L;
        onChanged();
        return this;
      }

      private long numWorkSteal_ ;
      /**
       * <code>optional int64 numWorkSteal = 10;</code>
       */
      public boolean hasNumWorkSteal() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 numWorkSteal = 10;</code>
       */
      public long getNumWorkSteal() {
        return numWorkSteal_;
      }
      /**
       * <code>optional int64 numWorkSteal = 10;</code>
       */
      public Builder setNumWorkSteal(long value) {
        bitField0_ |= 0x00000200;
        numWorkSteal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 numWorkSteal = 10;</code>
       */
      public Builder clearNumWorkSteal() {
        bitField0_ = (bitField0_ & ~0x00000200);
        numWorkSteal_ = 0L;
        onChanged();
        return this;
      }

      private long numWorkStealFail_ ;
      /**
       * <code>optional int64 numWorkStealFail = 11;</code>
       */
      public boolean hasNumWorkStealFail() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int64 numWorkStealFail = 11;</code>
       */
      public long getNumWorkStealFail() {
        return numWorkStealFail_;
      }
      /**
       * <code>optional int64 numWorkStealFail = 11;</code>
       */
      public Builder setNumWorkStealFail(long value) {
        bitField0_ |= 0x00000400;
        numWorkStealFail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 numWorkStealFail = 11;</code>
       */
      public Builder clearNumWorkStealFail() {
        bitField0_ = (bitField0_ & ~0x00000400);
        numWorkStealFail_ = 0L;
        onChanged();
        return this;
      }

      private int numTaskWait_ ;
      /**
       * <code>optional int32 numTaskWait = 12;</code>
       */
      public boolean hasNumTaskWait() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 numTaskWait = 12;</code>
       */
      public int getNumTaskWait() {
        return numTaskWait_;
      }
      /**
       * <code>optional int32 numTaskWait = 12;</code>
       */
      public Builder setNumTaskWait(int value) {
        bitField0_ |= 0x00000800;
        numTaskWait_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numTaskWait = 12;</code>
       */
      public Builder clearNumTaskWait() {
        bitField0_ = (bitField0_ & ~0x00000800);
        numTaskWait_ = 0;
        onChanged();
        return this;
      }

      private int numTaskReady_ ;
      /**
       * <code>optional int32 numTaskReady = 13;</code>
       */
      public boolean hasNumTaskReady() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 numTaskReady = 13;</code>
       */
      public int getNumTaskReady() {
        return numTaskReady_;
      }
      /**
       * <code>optional int32 numTaskReady = 13;</code>
       */
      public Builder setNumTaskReady(int value) {
        bitField0_ |= 0x00001000;
        numTaskReady_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numTaskReady = 13;</code>
       */
      public Builder clearNumTaskReady() {
        bitField0_ = (bitField0_ & ~0x00001000);
        numTaskReady_ = 0;
        onChanged();
        return this;
      }

      private int numCoreAvilable_ ;
      /**
       * <code>optional int32 numCoreAvilable = 14;</code>
       */
      public boolean hasNumCoreAvilable() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 numCoreAvilable = 14;</code>
       */
      public int getNumCoreAvilable() {
        return numCoreAvilable_;
      }
      /**
       * <code>optional int32 numCoreAvilable = 14;</code>
       */
      public Builder setNumCoreAvilable(int value) {
        bitField0_ |= 0x00002000;
        numCoreAvilable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numCoreAvilable = 14;</code>
       */
      public Builder clearNumCoreAvilable() {
        bitField0_ = (bitField0_ & ~0x00002000);
        numCoreAvilable_ = 0;
        onChanged();
        return this;
      }

      private int numAllCore_ ;
      /**
       * <code>optional int32 numAllCore = 15;</code>
       */
      public boolean hasNumAllCore() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional int32 numAllCore = 15;</code>
       */
      public int getNumAllCore() {
        return numAllCore_;
      }
      /**
       * <code>optional int32 numAllCore = 15;</code>
       */
      public Builder setNumAllCore(int value) {
        bitField0_ |= 0x00004000;
        numAllCore_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 numAllCore = 15;</code>
       */
      public Builder clearNumAllCore() {
        bitField0_ = (bitField0_ & ~0x00004000);
        numAllCore_ = 0;
        onChanged();
        return this;
      }

      private long outputSize_ ;
      /**
       * <code>optional int64 outputSize = 16;</code>
       */
      public boolean hasOutputSize() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional int64 outputSize = 16;</code>
       */
      public long getOutputSize() {
        return outputSize_;
      }
      /**
       * <code>optional int64 outputSize = 16;</code>
       */
      public Builder setOutputSize(long value) {
        bitField0_ |= 0x00008000;
        outputSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 outputSize = 16;</code>
       */
      public Builder clearOutputSize() {
        bitField0_ = (bitField0_ & ~0x00008000);
        outputSize_ = 0L;
        onChanged();
        return this;
      }

      private long submitTime_ ;
      /**
       * <code>optional int64 submitTime = 17;</code>
       */
      public boolean hasSubmitTime() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional int64 submitTime = 17;</code>
       */
      public long getSubmitTime() {
        return submitTime_;
      }
      /**
       * <code>optional int64 submitTime = 17;</code>
       */
      public Builder setSubmitTime(long value) {
        bitField0_ |= 0x00010000;
        submitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 submitTime = 17;</code>
       */
      public Builder clearSubmitTime() {
        bitField0_ = (bitField0_ & ~0x00010000);
        submitTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:matrix.protocol.Value)
    }

    static {
      defaultInstance = new Value(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:matrix.protocol.Value)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_matrix_protocol_Value_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_matrix_protocol_Value_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmetazht.proto\022\017matrix.protocol\"\335\002\n\005Val" +
      "ue\022\n\n\002id\030\001 \002(\t\022\020\n\010inDegree\030\002 \001(\003\022\017\n\007pare" +
      "nts\030\003 \003(\t\022\020\n\010children\030\004 \003(\t\022\024\n\014dataNameL" +
      "ist\030\005 \003(\t\022\020\n\010dataSize\030\006 \003(\003\022\023\n\013allDataSi" +
      "ze\030\007 \001(\003\022\022\n\ntaskLength\030\010 \001(\003\022\022\n\nnumTaskF" +
      "in\030\t \001(\003\022\024\n\014numWorkSteal\030\n \001(\003\022\030\n\020numWor" +
      "kStealFail\030\013 \001(\003\022\023\n\013numTaskWait\030\014 \001(\005\022\024\n" +
      "\014numTaskReady\030\r \001(\005\022\027\n\017numCoreAvilable\030\016" +
      " \001(\005\022\022\n\nnumAllCore\030\017 \001(\005\022\022\n\noutputSize\030\020" +
      " \001(\003\022\022\n\nsubmitTime\030\021 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_matrix_protocol_Value_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_matrix_protocol_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_matrix_protocol_Value_descriptor,
        new java.lang.String[] { "Id", "InDegree", "Parents", "Children", "DataNameList", "DataSize", "AllDataSize", "TaskLength", "NumTaskFin", "NumWorkSteal", "NumWorkStealFail", "NumTaskWait", "NumTaskReady", "NumCoreAvilable", "NumAllCore", "OutputSize", "SubmitTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
